### ISSUE TITLE
I put my address ,but i did not get no sem。

### ISSUE THREAD

**Issue by likaigithub** [honeycrypto/semux.org-backend#1]
hi,dev,I put my address in FAUCET,but i got no sem.Should i run my wallet on testnet?if so,how to run my wallet on testnet?My os is win10,and wallet is v1.0.0.

**Comment by honeycrypto** [comment]
Hi @likaigithub sure, you need to run your wallet in testnet and download testnet blockchain. You can achieve this by adding this flag `./semux-gui.sh --network testnet` I suggest you to use different folder for testnet wallet.
